// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Q-lVg_ae1AT9BEtl5qroFNGC1Clon30',
    appId: '1:158993130850:web:9c52cf5906648f82edb83b',
    messagingSenderId: '158993130850',
    projectId: 'e-commerce-app-b9580',
    authDomain: 'e-commerce-app-b9580.firebaseapp.com',
    storageBucket: 'e-commerce-app-b9580.appspot.com',
    measurementId: 'G-5M5T8R8D2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBzX_xzmG8rFpaHmrYSqki7jRVz8pOqiM',
    appId: '1:158993130850:android:4a346e86be7c3a44edb83b',
    messagingSenderId: '158993130850',
    projectId: 'e-commerce-app-b9580',
    storageBucket: 'e-commerce-app-b9580.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHmvjf6SjqjCDMqp8kDILK49EzTqJ3AVg',
    appId: '1:158993130850:ios:98799abebbc8dba3edb83b',
    messagingSenderId: '158993130850',
    projectId: 'e-commerce-app-b9580',
    storageBucket: 'e-commerce-app-b9580.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHmvjf6SjqjCDMqp8kDILK49EzTqJ3AVg',
    appId: '1:158993130850:ios:98799abebbc8dba3edb83b',
    messagingSenderId: '158993130850',
    projectId: 'e-commerce-app-b9580',
    storageBucket: 'e-commerce-app-b9580.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4Q-lVg_ae1AT9BEtl5qroFNGC1Clon30',
    appId: '1:158993130850:web:78b2e9576f0018a6edb83b',
    messagingSenderId: '158993130850',
    projectId: 'e-commerce-app-b9580',
    authDomain: 'e-commerce-app-b9580.firebaseapp.com',
    storageBucket: 'e-commerce-app-b9580.appspot.com',
    measurementId: 'G-7F86PS1WMG',
  );
}
